
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 07 02:07:57 CET 2016
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 41;
  public static final int CONST = 6;
  public static final int CHAR = 17;
  public static final int EQUALS = 33;
  public static final int LPAREN = 39;
  public static final int SEMI_COMMA = 36;
  public static final int LESS = 29;
  public static final int MINUS = 21;
  public static final int RPAREN = 40;
  public static final int GREQ = 28;
  public static final int GRE = 27;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int COMMA = 37;
  public static final int BOOL = 18;
  public static final int CLASS = 4;
  public static final int INC = 34;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 42;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 22;
  public static final int NUMBER = 16;
  public static final int MOD = 24;
  public static final int NEQ = 26;
  public static final int BREAK = 3;
  public static final int IDENT = 15;
  public static final int VOID = 12;
  public static final int EQ = 25;
  public static final int LBRACE = 43;
  public static final int ELSE = 5;
  public static final int STOP = 38;
  public static final int READ = 10;
  public static final int WHILE = 13;
  public static final int RBRACE = 44;
  public static final int EXTENDS = 14;
  public static final int LEQ = 30;
  public static final int STRING = 19;
  public static final int DEC = 35;
  public static final int PRINT = 9;
}

